on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ZMK
      run: west build -b dao -- -DZMK_CONFIG="../config/lostineverland" -DZMK_KEYMAP="lostineverland/keymap.yaml"
      env:
        ZEPHYR_BASE: ""
